// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpvnplugljwxrqibwvvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwdm5wbHVnbGp3eHJxaWJ3dnZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5ODg3MjAsImV4cCI6MjA1NTU2NDcyMH0.q29ynM6fccIwVas4gAFFGSkq0h1nfyfUVhuTdUlaVTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);